In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\rakesh\anaconda3\envs\new-ml\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rakesh\anaconda3\envs\new-ml\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rakesh\anaconda3\envs\new-ml\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\rakesh\anaconda3\envs\new-ml\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\rakesh\anaconda3\envs\new-ml\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

## Working with JSON

In [5]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [10]:
pd.read_json('https://jsonplaceholder.typicode.com/todos')

     userId   id                                              title  completed
0         1    1                                 delectus aut autem      False
1         1    2                 quis ut nam facilis et officia qui      False
2         1    3                                fugiat veniam minus      False
3         1    4                                   et porro tempora       True
4         1    5  laboriosam mollitia et enim quasi adipisci qui...      False
..      ...  ...                                                ...        ...
195      10  196                consequuntur aut ut fugit similique       True
196      10  197                  dignissimos quo nobis earum saepe       True
197      10  198                       quis eius est sint explicabo       True
198      10  199                       numquam repellendus a magnam       True
199      10  200                       ipsam aperiam voluptates qui      False

[200 rows x 4 columns]

## Working with SQL